version: "3.3"
services:
  helloworld-nodejs:
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    environment:
      - OTEL_SERVICE_NAME=helloworld
      - SPLUNK_METRICS_ENABLED=true
      - SPLUNK_PROFILER_ENABLED=true
      - SPLUNK_PROFILER_MEMORY_ENABLED=true
    ports:
      - "8080:8080"
    image: ghcr.io/splunk/helloworld-nodejs:1.0
networks: {}