clusterName: aks-test
splunkObservability:
  infrastructureMonitoringEventsEnabled: true
  realm: <REALM>
  accessToken: <ACCESS TOKEN>
  metricsEnabled: true
  logsEnabled: true
  tracesEnabled: true
  profilingEnabled: true
gateway:
  enabled: false
environment: test
distribution: "aks"
cloudProvider: "azure"
isWindows: false
operatorcrds:
  install: true
operator:
  enabled: true
  nodeSelector:
    kubernetes.io/os: linux
agent:
  discovery:
    enabled: true
splunkPlatform:
  endpoint: <HEC URL>
  token: <HEC TOKEN>
agent:
  config:
    receivers:
      kubeletstats:
        # this is required as the Kubelet API server in AKS uses self-signed certificates
        insecure_skip_verify: true
      receiver_creator:
        receivers:
          # example of how to capture coredns metrics using the prometheus receiver
          prometheus/coredns:
            config:
              config:
                scrape_configs:
                  - job_name: coredns
                    static_configs:
                      - targets:
                          - '`endpoint`:9153'
            rule: type == "pod" && labels["k8s-app"] == "kube-dns"
        watch_observers: [k8s_observer]