import { Product } from '../models/types';

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Celestron NexStar 127SLT Telescope',
    description:
      'Computerized telescope with fully automated GoTo mount and SkyAlign technology',
    price: 649.99,
    imageUrl:
      'https://images.unsplash.com/photo-1446941611757-91d2c3bd3d45?w=500&h=500&fit=crop',
    category: 'Telescopes',
    brand: 'Celestron',
    rating: 4.5,
    reviewCount: 123,
    inStock: true,
    specifications: 'Focal Length: 1500mm, Aperture: 127mm, Magnification: 59x-236x',
  },
  {
    id: '2',
    name: 'Orion SkyQuest XT8 Classic',
    description: '8-inch Dobsonian reflector telescope perfect for deep-sky observation',
    price: 399.99,
    imageUrl:
      'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=500&h=500&fit=crop',
    category: 'Telescopes',
    brand: 'Orion',
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    specifications: 'Focal Length: 1200mm, Aperture: 203mm, F-ratio: f/5.9',
  },
  {
    id: '3',
    name: 'Celestron Omni 32mm Eyepiece',
    description: 'High-quality Plössl eyepiece with 4-element design',
    price: 89.99,
    imageUrl:
      'https://images.unsplash.com/photo-1608178398319-48f814d0750c?w=500&h=500&fit=crop&auto=format',
    category: 'Eyepieces',
    brand: 'Celestron',
    rating: 4.3,
    reviewCount: 45,
    inStock: true,
    specifications: 'Focal Length: 32mm, Apparent FOV: 52°, Eye Relief: 20mm',
  },
  {
    id: '4',
    name: 'Turn Left at Orion Book',
    description: "A beginner's guide to finding and observing celestial objects",
    price: 24.99,
    imageUrl:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop',
    category: 'Books',
    brand: 'Cambridge University Press',
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    specifications: 'Pages: 280, Edition: 5th, Publisher: Cambridge University Press',
  },
  {
    id: '5',
    name: 'Red LED Flashlight',
    description: 'Astronomy red light flashlight to preserve night vision',
    price: 15.99,
    imageUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
    category: 'Accessories',
    brand: 'AstroGear',
    rating: 4.2,
    reviewCount: 67,
    inStock: true,
    specifications: 'LED Type: Red, Battery: 3x AAA, Runtime: 50 hours',
  },
  {
    id: '6',
    name: 'Star Chart Planisphere',
    description: 'Rotating star chart showing the night sky for any date and time',
    price: 12.99,
    imageUrl:
      'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=500&h=500&fit=crop',
    category: 'Accessories',
    brand: 'SkyGuide',
    rating: 4.1,
    reviewCount: 34,
    inStock: true,
    specifications: 'Size: 11 inch diameter, Latitude: 40-50° North, Material: Cardboard',
  },
  {
    id: '7',
    name: 'Orion 25mm Plössl Eyepiece',
    description: 'Classic 4-element Plössl design with excellent color correction',
    price: 69.99,
    imageUrl:
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=500&fit=crop&auto=format',
    category: 'Eyepieces',
    brand: 'Orion',
    rating: 4.4,
    reviewCount: 78,
    inStock: true,
    specifications: 'Focal Length: 25mm, Apparent FOV: 50°, Eye Relief: 17mm',
  },
  {
    id: '8',
    name: 'Meade Super Plössl 15mm Eyepiece',
    description: 'Premium multi-coated eyepiece for crisp, clear views',
    price: 95.99,
    imageUrl:
      'https://images.unsplash.com/photo-1574116294792-218bec4b9c55?w=500&h=500&fit=crop&auto=format',
    category: 'Eyepieces',
    brand: 'Meade',
    rating: 4.6,
    reviewCount: 92,
    inStock: true,
    specifications: 'Focal Length: 15mm, Apparent FOV: 52°, Eye Relief: 12mm',
  },
];
