agent:
  config:
    receivers:
      receiver_creator:
        # Name of the extensions to watch for endpoints to start and stop.
        watch_observers: [ k8s_observer ]
        receivers:
          prometheus:
            config:
              config:
                scrape_configs:
                  - job_name: gpu-metrics
                    static_configs:
                      - targets:
                          - '`endpoint`:9400'
            rule: type == "pod" && labels["app"] == "nvidia-dcgm-exporter"
    service:
      pipelines:
        metrics/nvidia-gpu-metrics:
          exporters:
            - signalfx
          processors:
            - memory_limiter
            - batch
            - resourcedetection
            - resource
          receivers:
            - receiver_creator
