apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: splunk-argo-rollouts-example
spec:
  replicas: 3
  strategy:
    canary:
      analysis:
        templates:
          - templateName: check-splunk-metrics
        startingStep: 2 # delay starting analysis run until setWeight: 40%
      steps:
        - setWeight: 20
        - pause: {duration: 1m}
        - setWeight: 40
        - pause: {duration: 1m}
        - setWeight: 60
        - pause: {duration: 1m}
        - setWeight: 80
        - pause: {duration: 1m}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: doorgame
  template:
    metadata:
      labels:
        app: doorgame
    spec:
      containers:
        - name: doorgame
          image: ghcr.io/splunk/doorgame:1.0
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: PORT
              value: "9090"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4318"
            - name: OTEL_SERVICE_NAME
              value: "doorgame"
          resources:
            requests:
              cpu: 200m
              memory: 2048Mi
            limits:
              cpu: 300m
              memory: 4096Mi