model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_base: https://api.openai.com/v1/
      api_key: os.environ/OPENAI_API_KEY
      rpm: 6      # Rate limit for this deployment: in requests per minute (rpm)

litellm_settings:
  callbacks: ["otel"]