apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing: {} # disable legacy MeshConfig tracing options
    extensionProviders:
      - name: "zipkin"
        zipkin:
          service: splunk-otel-collector-agent.default.svc.cluster.local
          port: 9411
