apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    # Requires Splunk Log Observer
    accessLogFile: /dev/stdout
    # Requires Splunk APM
    enableTracing: true
    defaultConfig:
      tracing:
        max_path_tag_length: 99999
        sampling: 100
        zipkin:
          address: $(HOST_IP):9411
        custom_tags:
          environment.deployment:
            literal:
              value: test