apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-west-2
  version: "1.31"
  tags:
    splunkit_environment_type: non-prd
    splunkit_data_classification: private

nodeGroups:
  - name: eks-workers
    instanceType: t3.large
    amiFamily: Ubuntu2204
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 100
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/eks_us_west_2_id_rsa.pub