apiVersion: apps/v1
kind: Deployment
metadata:
  name: doorgame
spec:
  selector:
    matchLabels:
      app: doorgame
  template:
    metadata:
      labels:
        app: doorgame
#      annotations:
#        splunk.com/exclude: "true"
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
        - name: doorgame
          image: ghcr.io/splunk/doorgame:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4318"
            - name: OTEL_SERVICE_NAME
              value: "doorgame"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
            - name: SPLUNK_PROFILER_ENABLED
              value: "true"
            - name: SPLUNK_PROFILER_MEMORY_ENABLED
              value: "true"
          resources:
            requests:
              cpu: 150m
              memory: 2048Mi
            limits:
              cpu: 300m
              memory: 4096Mi
---
apiVersion: v1
kind: Service
metadata:
  name: doorgame
spec:
  type: LoadBalancer
  selector:
    app: doorgame
  ports:
    - protocol: TCP
      port: 81
      targetPort: 9090